export const type = {
  GET_COIN_EXCHANGES_REQUEST: "GET_COIN_EXCHANGES_REQUEST",
  GET_COIN_EXCHANGES_SUCCESS: "GET_COIN_EXCHANGES_SUCCESS",
  GET_COIN_EXCHANGES_ERROR: "GET_COIN_EXCHANGES_ERROR",
};
